### ISSUE TITLE
Release and open your sources for contributions

### ISSUE THREAD

**Issue by rodrigotm** [soundcloudify/soundcloudify.github.io#3]
If you post your project in github for contributions,  you should open your codes. I'd like to help this project.

**Comment by rodrigotm** [comment]
:|

**Comment by ptgamr** [comment]
Hi @rodrigotm , sorry for getting back this late. Please feel free to give a help. The contributions list is already recorded by GitHub if you submit a pull request :+1:

**Comment by rodrigotm** [comment]
Sorry, I had not seen the development branch
